### PR TITLE
fixed services.yml after exchange options introduced

### PR DESCRIPTION
**Pull request by mente**

### CODE REVIEW

**Comment by mente** [comment]
Actually without this fix bundle doesn't work at al

**Comment by mguillermin** [comment]
:+1:

**Comment by mguillermin** [comment]
@omansour @fabdsp @mikaelrandy could you review this ?
This fix is quite urgent because the actual release (1.8.0) is broken.

**Comment by fabdsp** [comment]
:+1:

**Comment by fabdsp** [comment]
v1.8.2

**Pull request merged**
