### PR TITLE
[RFR] create queue in producer + add options

### PR DESCRIPTION
**Pull request by lepiaf**
Hi,

Like https://github.com/videlalvaro/rabbitmqbundle, it would be nice to create the queue when publishing a message into producer. 

Thanks.

Thierry

### CODE REVIEW

**Comment by fabdsp** [comment]
:+1:  thx !

**Comment by ch3ric** [comment]
:+1:

**Comment by mojoLyon** [comment]
:+1:

**Comment by mguillermin** [comment]
:+1:

**Comment by fabdsp** [comment]
Tag 1.6.0 (soon with #17 )

**Comment by fabdsp** [comment]
v1.6.0

**Pull request merged**
