### PR TITLE
Fixing README.md.

### PR DESCRIPTION
**Pull request by NiR-**
* Replacing bad m6web service prefix in the README.md.
* `ocramius/proxy-manager` ~0.5 => ~1.0

### CODE REVIEW

**Comment by mikaelrandy** [comment]
Seems good to me :+1:

**Comment by fabdsp** [comment]
:+1:

**Comment by mojoLyon** [comment]
Thanks :+1:

**Comment by mikaelrandy** [comment]
v1.3.1

**Pull request merged**
