### PR TITLE
Allow to override routingKeys in the publish() method

### PR DESCRIPTION
**Pull request by mguillermin**
This is useful for publishing a message with a dynamically computed routingKey.

### CODE REVIEW

**Comment by omansour** [comment]
:+1:

**Comment by soixante** [comment]
:+1:

**Comment by mikaelrandy** [comment]
:+1:

**Comment by jdohuutin** [comment]
:+1:

**Comment by mikaelrandy** [comment]
Can you update the README to explain this upgrade ?

**Comment by mguillermin** [comment]
v1.4.0

**Pull request merged**
