### PR TITLE
Add possibility to disable event dispatcher

### PR DESCRIPTION
**Pull request by vladylen**

### CODE REVIEW

**Comment by omansour** [comment]
:+1:

**Comment by mikaelrandy** [comment]
Ok on the principle, but out of curiosity, what's the use case that requires this feature?

**Comment by vladylen** [comment]
\M6Web\Bundle\AmqpBundle\Amqp\AbstractAmqp::setEventDispatcher
this function takes around 2 ms and dispatching event on each rabbitmq publishing takes a little less than 1 ms, but I have not use this events at all in my system and saving this time make sense for me

**Comment by t-geindre** [comment]
:+1:

**Comment by mikaelrandy** [comment]
Thank you for your explanation, it's obviously a valid workaround

**Pull request merged**
